# Stubs for indexes (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
from typing import Any, Optional, Dict, Text

from pynamodb.indexes import Index as PynamoDBIndex


class Index(PynamoDBIndex):
    Meta: Any
    def __init__(self) -> None: ...
    @classmethod
    async def count(cls, hash_key, consistent_read: bool = ..., **filters) -> int: ...
    @classmethod
    async def query(
        cls,
        hash_key,
        scan_index_forward: Optional[Any] = ...,
        consistent_read: bool = ...,
        limit: Optional[Any] = ...,
        last_evaluated_key: Optional[Dict[Text, Dict[Text, Any]]] = ...,
        attributes_to_get: Optional[Any] = ...,
        **filters,
    ): ...

class GlobalSecondaryIndex(Index): ...
class LocalSecondaryIndex(Index): ...
